language: python
python:
  - "2.7"
before_install:
  - pip install codecov
install:
  - cp npoed_sso_edx/local_settings.example npoed_sso_edx/local_settings.py
  - pip install -r requirements.txt
script:
  - ./manage.py test
after_success:
  - codecov
